---
title: "resim_plots"
output: html_document
date: "2025-10-22"
---

## Load libraries and functions

```{r echo=FALSE}
library(here)
source(here("scripts", "01_packages.R"))
source(here("scripts", "02b_definedelays.R"))
source(here("R", "funcs_data.R"))
source(here("R", "generate_scores_func.R"))
source(here("R", "plots_baseline.R"))
source(here("R", "lshtm_theme.R"))
```

## Figure 1: CRPS across gen time and inc period assumptions - Rt and case forecasts

### COVID-LIKE

#### Load Data

```{r echo=FALSE}
covid_resim_data <- read_latest(here("data"), "covid_sim_data")
rt_covid <- readRDS(here("data", "rt_covid.rds"))
```

#### Load Forecasts

```{r echo=FALSE}
covid_resim_samples <- read_latest(here("results/sim"), "res_covid_resim_latest_all_samples")
covid_resim_id <- read_latest(here("results/sim"), "res_covid_resim_latest_all_id")
covid_resim_R <- read_latest(here("results/sim"), "res_covid_resim_latest_all_R")

rt_covid <- rt_covid |>
  select(date, median) |>
  rename(R=median) |>
  mutate(scen=1)
```

#### Generate Scores

```{r echo=FALSE}
covid_scores_cases <- generate_scores_cases(covid_resim_samples, covid_resim_id, covid_resim_data) |>
  mutate(scen=1,
         rt_opts="latest",
         rt_traj="resim",
         ur="y")

covid_scores_rt <- generate_scores_rt(covid_resim_R, covid_resim_id, rt_covid) |>
  mutate(scen=1,
         rt_opts="latest",
         rt_traj="resim",
         ur="y")
```

#### Create Plots

```{r}
covid_caseplots <- plot_baseline_cases(covid_resim_samples,
                    covid_resim_id,
                    covid_resim_data,
                    covid_scores_cases,
                    forecast_freq = 4
                    )

covid_caseplots$final_plot
covid_caseplots$barchart_mean_gen_time
covid_caseplots$barchart_mean_inc_period
```

### EBOLA-LIKE

#### Load Data

```{r echo=FALSE}
ebola_resim_data <- read_latest(here("data"), "ebola_sim_data")
rt_ebola <- readRDS(here("data", "rt_ebola.rds"))
```

#### Load Forecasts

```{r echo=FALSE}
ebola_resim_samples <- read_latest(here("results/sim"), "res_ebola_resim_latest_all_samples")
ebola_resim_id <- read_latest(here("results/sim"), "res_ebola_resim_latest_all_id")
ebola_resim_R <- read_latest(here("results/sim"), "res_ebola_resim_latest_all_R")

rt_ebola <- rt_ebola |>
  select(date, R) |>
  mutate(scen=1)
```

#### Generate Scores

```{r echo=FALSE}
ebola_scores_cases <- generate_scores_cases(ebola_resim_samples, ebola_resim_id, ebola_resim_data) |>
  mutate(scen=1,
         rt_opts="latest",
         rt_traj="resim",
         ur="y")

ebola_scores_rt <- generate_scores_rt(ebola_resim_R, ebola_resim_id, rt_ebola) |>
  mutate(scen=1,
         rt_opts="latest",
         rt_traj="resim",
         ur="y")
```

#### Create Plots

```{r}
ebola_caseplots <- plot_baseline_cases(ebola_resim_samples,
                               ebola_resim_id,
                               ebola_resim_data,
                               ebola_scores_cases,
                               forecast_freq = 4
)

ebola_caseplots$final_plot
ebola_caseplots$barchart_mean_gen_time
ebola_caseplots$barchart_mean_inc_period
```

### CHOLERA-LIKE

#### Load Data

```{r echo=FALSE}
cholera_resim_data <- read_latest(here("data"), "cholera_sim_data")
rt_cholera <- readRDS(here("data", "rt_cholera.rds"))
```

#### Load Forecasts

```{r echo=FALSE}
cholera_resim_samples <- read_latest(here("results/sim"), "res_cholera_resim_latest_all_samples")
cholera_resim_id <- read_latest(here("results/sim"), "res_cholera_resim_latest_all_id")
cholera_resim_R <- read_latest(here("results/sim"), "res_cholera_resim_latest_all_R")

rt_cholera <- rt_cholera |>
  select(date, R) |>
  mutate(scen=1)
```

#### Generate Scores

```{r echo=FALSE}
cholera_scores_cases <- generate_scores_cases(cholera_resim_samples, cholera_resim_id, cholera_resim_data) |>
  mutate(scen=1,
         rt_opts="latest",
         rt_traj="resim",
         ur="y")

cholera_scores_rt <- generate_scores_rt(cholera_resim_R, cholera_resim_id, rt_cholera) |>
  mutate(scen=1,
         rt_opts="latest",
         rt_traj="resim",
         ur="y")
```

#### Create Plots

```{r}
cholera_caseplots <- plot_baseline_cases(cholera_resim_samples,
                               cholera_resim_id,
                               cholera_resim_data,
                               cholera_scores_cases,
                               forecast_freq = 4
)

cholera_caseplots$final_plot
cholera_caseplots$barchart_mean_gen_time
cholera_caseplots$barchart_mean_inc_period
```
